version: '3.5'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ads

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project_ads
    ports:
      - "8000:8000"
    depends_on:
      - db
